import streamlit as st
import google.generativeai as genai
from fpdf import FPDF
from gtts import gTTS
from PIL import Image
import tempfile
import os

# --- 1. PAGE CONFIGURATION ---
st.set_page_config(
    page_title="UK AI Health Agent",
    page_icon="🏥",
    layout="wide",
    initial_sidebar_state="expanded"
)

# Custom CSS for Medical Theme
st.markdown("""
<style>
    .stChatFloatingInputContainer {bottom: 20px;}
    .stButton>button {
        background-color: #28B463;
        color: white;
        border-radius: 10px;
        height: 50px;
        width: 100%;
    }
    .warning-box {
        background-color: #FFCDD2;
        color: #C62828;
        padding: 15px;
        border-radius: 10px;
        border: 1px solid #C62828;
        font-weight: bold;
    }
</style>
""", unsafe_allow_html=True)

# --- 2. SETUP & SESSION STATE ---

# Load API Key from Streamlit Secrets
try:
    if "GEMINI_API_KEY" in st.secrets:
        genai.configure(api_key=st.secrets["GEMINI_API_KEY"])
    else:
        st.error("⚠️ API Key missing! Please set GEMINI_API_KEY in Streamlit Secrets.")
except Exception as e:
    st.error(f"Configuration Error: {e}")

# Initialize Session State
if "messages" not in st.session_state:
    st.session_state.messages = [
        {"role": "assistant", "content": "Hello! I am your AI Health Assistant (UK Edition).\nTo begin, please tell me your **Name** and **Age**."}
    ]
if "chat_phase" not in st.session_state:
    st.session_state.chat_phase = "onboarding" 

# --- 3. HELPER FUNCTIONS ---

def text_to_speech(text):
    """Generates audio for the agent response"""
    try:
        # Generate generic filename to avoid clutter
        tts = gTTS(text=text, lang='en', tld='co.uk')
        with tempfile.NamedTemporaryFile(delete=False, suffix=".mp3") as fp:
            tts.save(fp.name)
            return fp.name
    except:
        return None

class MedicalReport(FPDF):
    def header(self):
        self.set_font('Arial', 'B', 16)
        self.cell(0, 10, 'UK AI HEALTH SERVICE', 0, 1, 'C')
        self.set_font('Arial', 'I', 10)
        self.cell(0, 10, 'Digital Triage & Pharmacy Assistant', 0, 1, 'C')
        self.line(10, 30, 200, 30)
        self.ln(20)
    
    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.cell(0, 10, 'Generated by AI. Consult a GP for medical advice.', 0, 0, 'C')

def create_pdf(chat_history):
    pdf = MedicalReport()
    pdf.add_page()
    pdf.set_font('Arial', '', 11)
    
    for msg in chat_history:
        role = "PATIENT" if msg["role"] == "user" else "AI DOCTOR"
        # Handle audio message marker
        content = msg["content"]
        if "🎤" in content:
            content = "[Voice Message Sent by Patient]"
            
        clean_content = content.encode('latin-1', 'replace').decode('latin-1')
        
        pdf.set_font('Arial', 'B', 10)
        pdf.set_text_color(0, 100, 0) if role == "AI DOCTOR" else pdf.set_text_color(0, 0, 0)
        pdf.cell(0, 6, f"{role}:", 0, 1)
        
        pdf.set_font('Arial', '', 10)
        pdf.set_text_color(0)
        pdf.multi_cell(0, 6, clean_content)
        pdf.ln(3)
        
    return pdf.output(dest='S').encode('latin-1')

# --- 4. CORE INTELLIGENCE (UPDATED FOR AUDIO) ---

def process_input(prompt, image=None, audio_bytes=None):
    """
    Handles Text, Image, and Audio inputs using Gemini 1.5 Flash
    """
    
    # Emergency Check (Only possible on text)
    if prompt:
        emergency_keywords = ["chest pain", "heart attack", "cant breathe", "can't breathe", "suicide", "bleeding"]
        if any(word in prompt.lower() for word in emergency_keywords):
            return "🚨 **EMERGENCY ALERT:** This sounds critical. Please STOP using this AI. **Call 999** immediately or go to A&E."

    # Model Setup (Gemini 1.5 Flash supports Audio natively)
    model = genai.GenerativeModel('gemini-1.5-flash')
    
    # System Prompt
    system_instruction = "You are a polite UK AI Pharmacist. Keep answers short. Recommend OTC medicine if safe. Always advise seeing a GP."
    
    # Build Payload
    content = [system_instruction]
    
    if image:
        content.append(image)
        content.append("Analyze this image (symptom/prescription) and provide advice.")
    
    if audio_bytes:
        # Pass audio directly to Gemini
        content.append({
            "mime_type": "audio/wav",
            "data": audio_bytes
        })
        content.append("Listen to the patient's voice query and respond appropriately.")

    if prompt:
        content.append(f"User Query: {prompt}")
    
    # Generate Response
    try:
        response = model.generate_content(content)
        return response.text
    except Exception as e:
        return f"Error connecting to AI: {e}"

# --- 5. UI LAYOUT ---

# A. Sidebar
with st.sidebar:
    st.image("https://cdn-icons-png.flaticon.com/512/3063/3063176.png", width=80)
    st.title("Tools")
    
    st.markdown("### 📸 Vision Analysis")
    uploaded_file = st.file_uploader("Upload Image", type=["jpg", "png", "jpeg"])
    
    st.markdown("---")
    if st.button("📄 Download Report"):
        pdf_bytes = create_pdf(st.session_state.messages)
        st.download_button("Click to Save PDF", pdf_bytes, "Medical_Report.pdf", "application/pdf")
    
    st.markdown("---")
    if st.button("🔄 Reset Chat"):
        st.session_state.messages = []
        st.session_state.chat_phase = "onboarding"
        st.rerun()

# B. Main Chat
st.title("🏥 UK AI Health Assistant")
st.caption("Voice-Enabled • Vision-Capable • NHS Guidelines")

# Display History
for message in st.session_state.messages:
    with st.chat_message(message["role"]):
        st.markdown(message["content"])

# C. Input Handling (Text OR Audio)
prompt = st.chat_input("Type symptoms here...")
audio_value = st.audio_input("Or speak to the agent") 

# Logic Variables
input_text = None
input_audio_bytes = None

# Detect Input Type
if prompt:
    input_text = prompt
elif audio_value:
    input_audio_bytes = audio_value.getvalue() # Convert audio to bytes for Gemini
    input_text = "🎤 [Voice Message Sent]"

# Process if Input Exists
if input_text or input_audio_bytes:
    
    # 1. Display User Message
    st.session_state.messages.append({"role": "user", "content": input_text})
    with st.chat_message("user"):
        st.markdown(input_text)
        if input_audio_bytes:
            st.audio(audio_value) # Play back user's voice

    # 2. Handle Image
    image_data = None
    if uploaded_file:
        image_data = Image.open(uploaded_file)
        st.toast("Image attached for analysis", icon="📸")

    # 3. AI Processing
    with st.chat_message("assistant"):
        with st.spinner("Consulting AI Pharmacist..."):
            
            # Check phase for Onboarding (Name/Age) ONLY if using Text
            if st.session_state.chat_phase == "onboarding" and not input_audio_bytes:
                response_text = f"Thank you. Details noted: '{input_text}'.\n\nHow can I help you today? (Describe symptoms or upload a prescription)"
                st.session_state.chat_phase = "consultation"
            else:
                # Full AI Call (Text + Audio + Image)
                response_text = process_input(prompt, image_data, input_audio_bytes)

            # Display Response
            if "EMERGENCY" in response_text:
                st.markdown(f'<div class="warning-box">{response_text}</div>', unsafe_allow_html=True)
            else:
                st.markdown(response_text)
                
                # Generate & Play Audio Response
                audio_file = text_to_speech(response_text)
                if audio_file:
                    st.audio(audio_file, format="audio/mp3", start_time=0)

    # 4. Save AI Response to History
    st.session_state.messages.append({"role": "assistant", "content": response_text})
