import streamlit as st
import google.generativeai as genai
from fpdf import FPDF
from gtts import gTTS
from PIL import Image
import io
import os
import tempfile

# --- 1. PAGE CONFIGURATION (Medical Theme) ---
st.set_page_config(
    page_title="UK AI Health Agent",
    page_icon="🏥",
    layout="wide",
    initial_sidebar_state="expanded"
)

# Custom CSS for "Innovative" Look
st.markdown("""
<style>
    .stChatFloatingInputContainer {bottom: 20px;}
    .user-avatar {background-color: #2E86C1;}
    .assistant-avatar {background-color: #28B463;}
    h1 {color: #2E4053;}
    .stButton>button {
        background-color: #28B463;
        color: white;
        border-radius: 10px;
        height: 50px;
        width: 100%;
    }
    .warning-box {
        background-color: #FFCDD2;
        color: #C62828;
        padding: 15px;
        border-radius: 10px;
        border: 1px solid #C62828;
        font-weight: bold;
    }
</style>
""", unsafe_allow_html=True)

# --- 2. SETUP & SESSION STATE ---

# Load API Key from Streamlit Secrets
try:
    genai.configure(api_key=st.secrets["GEMINI_API_KEY"])
except:
    st.error("⚠️ API Key missing! Please set GEMINI_API_KEY in Streamlit Secrets.")

# Initialize Session State (Memory)
if "messages" not in st.session_state:
    st.session_state.messages = [
        {"role": "assistant", "content": "Hello! I am your AI Health Assistant (UK Edition).\nTo begin, please tell me your **Name** and **Age**."}
    ]
if "user_details" not in st.session_state:
    st.session_state.user_details = {}
if "chat_phase" not in st.session_state:
    st.session_state.chat_phase = "onboarding" # onboarding -> consultation

# --- 3. HELPER FUNCTIONS ---

def text_to_speech(text):
    """Generates audio for the agent"""
    try:
        tts = gTTS(text=text, lang='en', tld='co.uk')
        with tempfile.NamedTemporaryFile(delete=False, suffix=".mp3") as fp:
            tts.save(fp.name)
            return fp.name
    except:
        return None

class MedicalReport(FPDF):
    def header(self):
        self.set_font('Arial', 'B', 16)
        self.cell(0, 10, 'UK AI HEALTH SERVICE', 0, 1, 'C')
        self.set_font('Arial', 'I', 10)
        self.cell(0, 10, 'Digital Triage & Pharmacy Assistant', 0, 1, 'C')
        self.line(10, 30, 200, 30)
        self.ln(20)
    
    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.cell(0, 10, 'Generated by AI. Consult a GP for medical advice.', 0, 0, 'C')

def create_pdf(chat_history):
    pdf = MedicalReport()
    pdf.add_page()
    pdf.set_font('Arial', '', 11)
    
    for msg in chat_history:
        role = "PATIENT" if msg["role"] == "user" else "AI DOCTOR"
        content = msg["content"].encode('latin-1', 'replace').decode('latin-1')
        
        pdf.set_font('Arial', 'B', 10)
        if role == "AI DOCTOR":
            pdf.set_text_color(0, 100, 0) # Green
        else:
            pdf.set_text_color(0, 0, 0) # Black
            
        pdf.cell(0, 6, f"{role}:", 0, 1)
        pdf.set_font('Arial', '', 10)
        pdf.multi_cell(0, 6, content)
        pdf.ln(3)
        
    return pdf.output(dest='S').encode('latin-1')

# --- 4. CORE LOGIC ---

def process_input(prompt, image=None):
    # Emergency Check
    emergency_keywords = ["chest pain", "heart attack","accident", "cant breathe", "can't breathe", "suicide", "bleeding"]
    if any(word in prompt.lower() for word in emergency_keywords):
        return "🚨 **EMERGENCY ALERT:** This sounds critical. Please STOP using this AI. **Call 999 or 1122** immediately or go to A&E."

    # Model Configuration
    model = genai.GenerativeModel('gemini-1.5-flash') # Using 1.5 Flash for speed/cost
    
    # Context prompt
    system_prompt = "You are a polite internatonal AI Pharmacist. Keep answers short. Recommend OTC medicine if safe. Always advise seeing a GP."
    
    content = [system_prompt]
    if image:
        content.append(image)
        content.append("Analyze this image (symptom/prescription) and provide advice.")
    content.append(f"User Query: {prompt}")
    
    response = model.generate_content(content)
    return response.text

# --- 5. UI LAYOUT ---

# A. Sidebar (Tools)
with st.sidebar:
    st.image("https://cdn-icons-png.flaticon.com/512/3063/3063176.png", width=100)
    st.title("Patient Tools")
    
    st.markdown("### 📸 Vision Analysis")
    uploaded_file = st.file_uploader("Upload Prescription/Symptom", type=["jpg", "png", "jpeg"])
    
    st.markdown("---")
    st.markdown("### 📄 Reports")
    if st.button("Generate PDF Report"):
        pdf_bytes = create_pdf(st.session_state.messages)
        st.download_button(
            label="⬇️ Download PDF",
            data=pdf_bytes,
            file_name="Medical_Report.pdf",
            mime="application/pdf"
        )
    
    st.markdown("---")
    if st.button("Clear Consultation"):
        st.session_state.messages = []
        st.rerun()

# B. Main Chat Interface
st.title("🏥 AI Health Assistant ")
st.caption("Voice-Enabled • Vision-Capable • NHS Guidelines")

# Display Chat History
for message in st.session_state.messages:
    with st.chat_message(message["role"]):
        st.markdown(message["content"])

# C. Input Area
prompt = st.chat_input("Type your symptoms here...")
audio_value = st.audio_input("Or speak to the agent") # NEW STREAMLIT FEATURE

# Logic to handle input
input_text = None

if prompt:
    input_text = prompt
elif audio_value:
    # In a real deployed app, you'd send audio bytes to Gemini. 
    # For this simpler version, we assume audio triggers a generic check or 
    # you can integrate Whisper. For now, we will ask user to confirm text.
    st.info("🎤 Voice received! (Voice-to-Text requires OpenAI Whisper key, strictly text for this demo mode).")
    # To keep it working without paid keys, we rely on Text or Image mainly.

if input_text:
    # 1. User Message Display
    st.session_state.messages.append({"role": "user", "content": input_text})
    with st.chat_message("user"):
        st.markdown(input_text)

    # 2. Logic processing
    image_data = None
    if uploaded_file:
        image_data = Image.open(uploaded_file)
        st.toast("Image attached to analysis", icon="📸")

    # Phase Check
    if st.session_state.chat_phase == "onboarding":
        response_text = f"Thank you. I have noted your details: '{input_text}'.\n\nHow can I help you today? (Describe symptoms or upload a prescription)"
        st.session_state.chat_phase = "consultation"
    else:
        with st.spinner("Analyzing symptoms & checking pharmacy database..."):
            response_text = process_input(input_text, image_data)

    # 3. AI Response Display
    with st.chat_message("assistant"):
        # Check for Emergency
        if "EMERGENCY" in response_text:
            st.markdown(f'<div class="warning-box">{response_text}</div>', unsafe_allow_html=True)
        else:
            st.markdown(response_text)
            
            # Audio Output
            audio_file = text_to_speech(response_text)
            if audio_file:
                st.audio(audio_file, format="audio/mp3")

    st.session_state.messages.append({"role": "assistant", "content": response_text})